FROM node:10.15.2-stretch-slim

RUN apt-get update && apt-get -y install \
  bzip2 \
  g++ \
  iputils-ping \
  make \
  net-tools \
  netcat \
  procps \
  python3 \
  vim \
  && apt-get clean && \
  rm -r /var/lib/apt/lists/*

ENV PATH $PATH:/node_modules/.bin
RUN npm install -g npm@6.9.0
COPY package.json package-lock.json /
RUN npm install

COPY . /app
WORKDIR /app
CMD [ "pm2-docker", "/api/process.yml" ]
