// Generated by CoffeeScript 1.12.7
var applyJenkinsLabel, labelName, logLabel, regExpFilters;

labelName = 'acm-dp-logging';

logLabel = GmailApp.getUserLabelByName(labelName);

regExpFilters = [/.*\s»\s.*Build\s#\s\d+\s/, /^[A-Z]*-[A-Z]* : .*\sstatus\sfor\s\d{4}-\d{2}-\d{2}$/];

applyJenkinsLabel = function() {
  var eachMessage, foundSubject, i, idx, j, len, len1, messages, subject, testSubject, thread, threads;
  testSubject = function(subject) {
    var i, len, regex;
    for (i = 0, len = regExpFilters.length; i < len; i++) {
      regex = regExpFilters[i];
      if ((subject + "").match(regex)) {
        return true;
      }
    }
    return false;
  };
  threads = GmailApp.search("in:inbox AND NOT label:" + labelName, 0, 25);
  if (threads.length <= 0) {
    return false;
  }
  for (idx = i = 0, len = threads.length; i < len; idx = ++i) {
    thread = threads[idx];
    messages = thread.getMessages();
    foundSubject = false;
    for (j = 0, len1 = messages.length; j < len1; j++) {
      eachMessage = messages[j];
      subject = eachMessage.getSubject();
      foundSubject = testSubject(subject);
      if (foundSubject) {
        continue;
      }
    }
    if (foundSubject) {
      console.log('Tag label > ', subject);
      thread.addLabel(logLabel);
    }
  }
  console.log(' == done ==');
  return true;
};
